version: "3.7"

services:
  flask:
    build: ./flask
    restart: always
    networks: 
      - "flask.network"
    environment:
      APP_NAME: "${APP_NAME}"
      API_KEY: "${API_KEY}"
      AUTH_KEY: "${AUTH_KEY}"
      CLIENT_ID: "${CLIENT_ID}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
    expose:
      - 8080
    deploy:
      replicas: 5

  nginx:
    build: ./nginx
    restart: always
    networks: 
      - "flask.network"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  mongo:
    image: mongo:3.6.1
    networks: 
      - "flask.network"
    ports:
      - "27017:27017"

networks: 
    flask.network: