version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      APP_NAME: "${APP_NAME}"
      API_KEY: "${API_KEY}"
      AUTH_KEY: "${AUTH_KEY}"
      CLIENT_ID: "${CLIENT_ID}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  mongo:
    image: mongo:3.6.1
    ports:
      - "27017:27017
